/* Address selection uses source-labelled catalog entries; manual input stays unverified. */
(function(){
 const norm=s=>String(s||'').toLowerCase().replaceAll('ё','е').replace(/^(?:ул\.?|улица|проспект|пр-кт|пр\.|пер\.?|переулок)\s+/,'').replace(/\s+/g,' ').trim();
 const lookup=value=>houseDB.find(x=>x.street===value||x.code===value)||houseDB.find(x=>norm(x.street)===norm(value)||(x.aliases||[]).some(a=>norm(a)===norm(value)));
 findStreet=lookup;
 // A user-supplied street name is searchable, without invented house numbers or GAR status.
 if(!lookup('Рублёвская'))houseDB.push({code:'local:rublevskaya',street:'ул. Рублёвская',aliases:['Рублевская'],houses:[],userProvided:true,sourceLabel:'Название добавлено по сообщению пользователя; номер дома укажите вручную.'});
 const cleanHouse=window.cleanHouseNumber=value=>String(value||'').trim().replace(/^(?:(?:домовладение|домовл|дмвлд|двлд|владение|влд|здание|зд|дом|участок|уч|д)\.?\s*)+(?=\d)/iu,'').trim();
 const houseOrder=new Intl.Collator('ru',{numeric:true,sensitivity:'base'});

 const sheet=document.querySelector('#addressModal .sheet');
 sheet.innerHTML='<h3>Адрес в Нальчике</h3><div class="notice">Справочник дополнен открытыми адресными данными. Полнота и актуальность всех домов не подтверждены. Если адреса нет, введите его вручную.</div><label class="formlabel" for="streetInput">Улица</label><input id="streetInput" class="input" placeholder="Например: Ленина или СНТ Мир" autocomplete="off"><div id="streetSuggestions"></div><label style="display:block;margin-top:12px"><input id="manualAddress" type="checkbox"> Моего адреса нет — ввести вручную</label><label class="formlabel" for="houseSelect">Дом</label><select id="houseSelect" class="input"><option value="">Сначала выберите адрес</option></select><label class="formlabel" for="manualHouse">Другой дом или участок — ввести номер</label><input id="manualHouse" class="input" placeholder="Например: 12, 12/1 или уч. 12"><div id="houseHint" class="muted"></div><label style="display:block;margin-top:12px"><input id="privateAddress" type="checkbox"> Частный дом / участок, без квартиры</label><label class="formlabel" for="apartmentInput">Квартира</label><input id="apartmentInput" class="input" placeholder="Номер квартиры"><div id="orgPreview"></div><div class="actions"><button class="btn secondary" onclick="closeAddress()">Отмена</button><button class="btn" onclick="saveAddress()">Сохранить</button></div>';
 const el=id=>document.getElementById(id);let chosen=null;
 function changed(){chosen=null;selectedHouse=null;el('houseSelect').replaceChildren(new Option('Выберите адрес из подсказок',''));el('houseHint').textContent='';el('orgPreview').textContent='';}
 suggestStreets=function(){changed();const q=norm(el('streetInput').value),box=el('streetSuggestions');box.replaceChildren();if(!q)return;const matches=houseDB.filter(x=>norm(x.street).includes(q)||(x.aliases||[]).some(a=>norm(a).includes(q))).sort((a,b)=>(norm(b.street)===q)-(norm(a.street)===q)).slice(0,20);for(const x of matches){const button=document.createElement('button');button.className='suggestion';button.style.cssText='display:block;width:100%;text-align:left;background:white';button.textContent=x.street;button.onclick=()=>chooseStreet(x.code||x.street);box.append(button);}if(!matches.length)box.textContent='Не найдено. Можно включить ручной ввод.';};
 fillHouses=function(x){chosen=x;selectedHouse=x;el('houseSelect').replaceChildren(new Option('Выберите дом или введите номер ниже',''));for(const h of [...new Set((x.houses||[]).filter(h=>! /^(?:Н|Ч|ВЛ|НД)\(/.test(h)).map(cleanHouse))].sort(houseOrder.compare)){el('houseSelect').add(new Option(h,h));}el('houseHint').textContent=x.sourceLabel||'Локальный справочник; полный перечень домов не подтверждён.';el('orgPreview').textContent='Управляющая организация будет показана только при наличии сведений для этого дома.';};
 chooseStreet=function(value){const x=lookup(value);if(!x)return;el('streetInput').value=x.street;el('manualAddress').checked=false;el('streetSuggestions').replaceChildren();fillHouses(x);};
 openAddress=function(){el('streetSuggestions').replaceChildren();el('addressModal').classList.add('show');el('streetInput').value=savedAddress?.street||'';el('apartmentInput').value=savedAddress?.isPrivate?'':savedAddress?.apartment||'';el('privateAddress').checked=!!savedAddress?.isPrivate;el('apartmentInput').disabled=el('privateAddress').checked;el('manualHouse').value='';changed();const x=savedAddress?.innerStreet?null:lookup(savedAddress?.catalogCode||savedAddress?.street||'');el('manualAddress').checked=!!savedAddress&&!x;if(x){el('streetInput').value=x.street;fillHouses(x);}if(savedAddress){const h=cleanHouse(savedAddress.house);if([...el('houseSelect').options].some(o=>o.value===h))el('houseSelect').value=h;else el('manualHouse').value=h||'';}};
 el('streetInput').oninput=suggestStreets;el('privateAddress').onchange=()=>{const checked=el('privateAddress').checked;el('apartmentInput').disabled=checked;if(checked)el('apartmentInput').value='';};
 el('manualHouse').oninput=()=>{if(el('manualHouse').value)el('houseSelect').value='';};el('houseSelect').onchange=()=>{if(el('houseSelect').value)el('manualHouse').value='';};
 window.addressSelection=function(){const typed=el('streetInput').value.trim(),manual=el('manualAddress').checked,x=chosen||lookup(typed),house=cleanHouse(el('manualHouse').value.trim()||el('houseSelect').value),isPrivate=el('privateAddress').checked,apartment=isPrivate?'':el('apartmentInput').value.trim();if(!typed||(!manual&&!x)||!house||(!isPrivate&&!apartment)){alert('Выберите адрес или включите ручной ввод, укажите дом и квартиру либо отметьте частный дом.');return null;}const street=manual?typed:x.street;const org=(!manual&&!x.userProvided)?findOrg(norm(street),house):null;return {street,house,apartment,isPrivate,innerStreet:'',catalogCode:manual?'':x.code||'',org:org?.org||'',orgSource:org?.source||'',addressSource:manual||x?.userProvided||el('manualHouse').value?'user':x.sourceLabel||'legacy-catalog',gar:manual?'':x.gar||''};};
 const previous=renderAll;renderAll=function(){previous();if(savedAddress?.isPrivate){el('apartmentTitle').textContent='Частный дом / участок · Нальчик';el('homeApartmentTitle').textContent='Нальчик · частный дом / участок';}if(savedAddress&&!savedAddress.org)el('orgCard').innerHTML='<div class="title">Управляющая организация</div><p class="muted">Сведения не подтверждены для этого адреса.</p>';};renderAll();
})();
