/* Explicit server save/restore. No local data leaves the browser before a user action. */
(function(){
 const keys=['mydomAddress','mydomAccounts','mydomManualBills','mydomResidentIssues','mydomWater','mydomMeterHistory','mydomApartmentsV1','mydomWelcomeDone','mydomHouseEvents'];
 const workspaceKeys=['mydomAddress','mydomAccounts','mydomManualBills','mydomResidentIssues','mydomWater','mydomMeterHistory'];
 let login=null,revision=null,remote=null,busy=false;
 const box=document.createElement('div');box.className='card';box.id='cloudAccount';document.getElementById('homeinfo').prepend(box);
 function status(message){document.getElementById('cloudStatus').textContent=message;}
 async function request(path,options={}){const response=await fetch('/api/'+path,{credentials:'same-origin',cache:'no-store',...options,headers:{'Content-Type':'application/json',...options.headers}});let data;try{data=await response.json();}catch(e){throw Error('Сервер недоступен. Локальные данные сохранены.');}if(!response.ok)throw Error(data.error||'Ошибка сервера');return data;}
 function snapshot(){const data=Object.fromEntries(keys.map(k=>[k,localStorage.getItem(k)]));if(data.mydomApartmentsV1){const registry=JSON.parse(data.mydomApartmentsV1),current=registry.homes.find(h=>h.id===registry.active);if(current){current.data=Object.fromEntries(workspaceKeys.map(k=>[k,data[k]]));current.address=JSON.parse(data.mydomAddress||'null');}data.mydomApartmentsV1=JSON.stringify(registry);}return data;}
 async function work(action){if(busy)return;busy=true;box.querySelectorAll('button').forEach(b=>b.disabled=true);try{await action();}catch(e){status(e.message);}finally{busy=false;box.querySelectorAll('button').forEach(b=>b.disabled=false);}}
 function render(){box.innerHTML='<div class="title">Учётная запись и сервер</div>'+(login?'<p>Вы вошли: <b>'+escapeHtml(login)+'</b></p><p class="muted">Сохраняются все квартиры. После изменений нажмите «Сохранить на сервер». Автоматическая синхронизация пока не включена.</p><div class="actions"><button id="cloudSave" class="btn">Сохранить на сервер</button><button id="cloudLoad" class="btn secondary">Загрузить с сервера</button></div><button id="cloudLogout" class="back" style="margin-top:18px">Выйти</button>':'<p class="muted">Войдите, чтобы сохранять квартиры и открывать их на другом устройстве. Локальные записи не отправляются автоматически.</p><label class="formlabel" for="cloudLogin">Логин (латиница)</label><input id="cloudLogin" class="input" autocomplete="username"><label class="formlabel" for="cloudPassword">Пароль (от 12 символов)</label><input id="cloudPassword" class="input" type="password" autocomplete="current-password"><label class="formlabel" for="cloudInvite">Код приглашения — только при регистрации</label><input id="cloudInvite" class="input" autocomplete="off"><div class="actions"><button id="cloudSignIn" class="btn">Войти</button><button id="cloudRegister" class="btn secondary">Создать аккаунт</button></div>')+'<div id="cloudStatus" class="notice" role="status" style="margin-top:12px">'+(login?'Проверяю серверную запись…':'Восстановление пароля по почте пока недоступно. Сохраните пароль.')+'</div>';
 addTransfer();
 if(login){document.getElementById('cloudSave').onclick=()=>work(save);document.getElementById('cloudLoad').onclick=()=>work(restore);document.getElementById('cloudLogout').onclick=()=>work(async()=>{await request('logout',{method:'POST',body:'{}'});login=null;revision=null;remote=null;render();status('Вы вышли. Локальные данные остались на устройстве.');});}
 else for(const [id,route]of [['cloudSignIn','login'],['cloudRegister','register']])document.getElementById(id).onclick=()=>work(async()=>{const b={login:document.getElementById('cloudLogin').value,password:document.getElementById('cloudPassword').value,invite:document.getElementById('cloudInvite').value};const result=await request(route,{method:'POST',body:JSON.stringify(b)});login=result.login;render();await inspect();});
 }
 function addTransfer(){
 const part=document.createElement('div');part.style.marginTop='16px';part.innerHTML='<div class="title">Перенос на другой адрес приложения</div><p class="muted">Скачайте копию квартир здесь и импортируйте её на серверном сайте. Файл содержит ваши личные данные.</p><div class="actions"><button class="btn secondary" id="exportLocalHomes">Скачать копию</button><label class="btn secondary">Импорт копии<input id="importLocalHomes" type="file" accept="application/json,.json" style="display:none"></label></div><div id="transferStatus" role="status"></div>';box.append(part);
 document.getElementById('exportLocalHomes').onclick=()=>{try{const blob=new Blob([JSON.stringify({format:'mydom-backup',version:1,data:snapshot()},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='mydom-apartments.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(e){document.getElementById('transferStatus').textContent='Не удалось создать копию: '+e.message;}};
 document.getElementById('importLocalHomes').onchange=async e=>{const file=e.target.files[0];if(!file)return;const message=document.getElementById('transferStatus');try{if(file.size>2*1024*1024)throw Error('Файл больше 2 МБ');const input=JSON.parse(await file.text());if(input.format!=='mydom-backup'||input.version!==1||!input.data||Array.isArray(input.data))throw Error('Нужна копия «Мой дом»');for(const [k,v]of Object.entries(input.data)){if(!keys.includes(k)||(v!==null&&typeof v!=='string'))throw Error('Неверный формат полей');if(v!==null&&!['mydomWater','mydomWelcomeDone'].includes(k))JSON.parse(v);}if(!confirm('Заменить локальные квартиры данными из файла? Прежняя копия сохранится в этом браузере. Данные на сервер не отправляются.'))return;const before=snapshot();localStorage.setItem('mydomBeforeCloudRestore',JSON.stringify({createdAt:new Date().toISOString(),data:before}));try{for(const k of keys){const v=input.data[k];if(v==null)localStorage.removeItem(k);else localStorage.setItem(k,v);}}catch(error){for(const k of keys){if(before[k]==null)localStorage.removeItem(k);else localStorage.setItem(k,before[k]);}throw error;}location.reload();}catch(error){message.textContent='Импорт не выполнен: '+error.message;}finally{e.target.value='';}};
 }
 async function inspect(){remote=await request('data');revision=remote.revision;status(remote.data?'На сервере есть данные от '+new Date(remote.updated).toLocaleString('ru-RU')+'. Можно загрузить их или явно заменить локальными.':'На сервере пока нет данных. Нажмите «Сохранить на сервер», чтобы перенести свои квартиры.');}
 async function save(){if(revision===null)throw Error('Сначала войдите заново, чтобы проверить серверную версию.');if(!confirm(remote?.data?'Заменить серверные данные всеми квартирами из этого браузера? При более новой серверной версии операция будет остановлена.':'Сохранить все квартиры из этого браузера в учётную запись '+login+'?'))return;const data=snapshot();const result=await request('data',{method:'PUT',body:JSON.stringify({revision,data})});revision=result.revision;remote={...result,data};status('Все квартиры сохранены на сервере · '+new Date(result.updated).toLocaleString('ru-RU'));}
 async function restore(){const latest=await request('data');if(!latest.data){status('На сервере пока нет данных. Локальные записи не изменены.');return;}if(!confirm('Заменить локальные квартиры данными учётной записи '+login+'? Перед заменой будет сохранена локальная резервная копия.'))return;
 const before=snapshot();localStorage.setItem('mydomBeforeCloudRestore',JSON.stringify({createdAt:new Date().toISOString(),data:before}));
 try{for(const k of keys){const value=latest.data[k];if(value==null)localStorage.removeItem(k);else localStorage.setItem(k,value);}}catch(e){for(const k of keys){if(before[k]==null)localStorage.removeItem(k);else localStorage.setItem(k,before[k]);}throw Error('Не удалось загрузить данные. Восстановлены прежние записи.');}location.reload();}
 // Only expose login when this origin actually serves the MyDom API.
 fetch('/api/health',{cache:'no-store'}).then(async r=>{if(!r.ok)throw Error();const data=await r.json();if(data.service!=='mydom')throw Error();for(const note of document.querySelectorAll('.local-note')){if(note.textContent.includes('Данные хранятся в этом браузере.'))note.textContent='Данные доступны в этом браузере. Серверная копия — в разделе «Ещё». Подключение к поставщикам пока недоступно.';}try{const session=await request('session');login=session.login;}catch(e){}render();if(login)await inspect();}).catch(()=>{box.innerHTML='<div class="title">Серверное хранение</div><p class="muted">На этом адресе сервер ещё не подключён. Данные сохраняются только в браузере.</p>';addTransfer();});
})();
